import * as num from './numbers.js';
import * as arr from './arrays.js';
import { Truthy, Falsy } from './booleans.js';
import * as thisKey from './thisKeyword.js';
import * as obj from './objects.js';
import * as bf from './functions/basicFunctions.js';
import * as ff from './functions/factoryFunctions.js';
import * as cf from './functions/constructorFunctions.js';
import * as vlc from './var_let_const.js';
import * as sps from './spread_syntax.js';
import * as rst from './rest_parameters.js';
import * as cnv from './conversions.js';
import * as wjons from './working_with_JSON.js';
import * as cls from './classes.js';
import * as mod from './modules.js';

//num.divide();
//Truthy();
//Falsy();
//thisKey.run();
//obj.run();
//ff.run();
//cf.run();
//vlc.run();
//bf.run();
arr.run();
//sps.run();
//rst.run();
//cnv.run();
//wjons.run();
//cls.run();
//mod.run();